/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaGuiD;
import javax.swing.JOptionPane;

/**
 *
 * @author WINDOWS
 */
public class K_Swing2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(K_Swing2.class.getName());
        private int total,jumlahpesanan;

    /**
     * Creates new form Swing2
     */
    public K_Swing2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        cbmieayam = new javax.swing.JCheckBox();
        cbbakso = new javax.swing.JCheckBox();
        cbnasigoreng = new javax.swing.JCheckBox();
        cbmartabak = new javax.swing.JCheckBox();
        tfmieayam = new javax.swing.JTextField();
        tfbakso = new javax.swing.JTextField();
        tfnasigoreng = new javax.swing.JTextField();
        tfmartabak = new javax.swing.JTextField();
        btnhitung = new javax.swing.JButton();
        btnbersih = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        tfhitung = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("MENU MAKANAN");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        cbmieayam.setText("Mie Ayam : 15000");
        cbmieayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmieayamActionPerformed(evt);
            }
        });

        cbbakso.setText("Bakso : 13000");
        cbbakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbaksoActionPerformed(evt);
            }
        });

        cbnasigoreng.setText("Nasi Goreng : 10000");
        cbnasigoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnasigorengActionPerformed(evt);
            }
        });

        cbmartabak.setText("Martabak : 17000");
        cbmartabak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmartabakActionPerformed(evt);
            }
        });

        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        btnbersih.setText("Bersih");
        btnbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbersihActionPerformed(evt);
            }
        });

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        jLabel1.setText("Hitung :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbmieayam)
                                    .addComponent(cbbakso)
                                    .addComponent(cbnasigoreng)
                                    .addComponent(cbmartabak))
                                .addGap(113, 113, 113))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(53, 53, 53)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfhitung, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfmartabak, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(tfnasigoreng)
                                .addComponent(tfmieayam, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfbakso, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnhitung, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnbersih, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnkeluar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmieayam)
                    .addComponent(tfmieayam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbakso)
                    .addComponent(tfbakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbnasigoreng)
                    .addComponent(tfnasigoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhitung))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfmartabak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmartabak)
                    .addComponent(btnbersih))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnkeluar)
                    .addComponent(tfhitung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        total = 0;

    try {
        if (cbmieayam.isSelected()) {
            jumlahpesanan = Integer.parseInt(tfmieayam.getText());
            total += jumlahpesanan * 15000;
        }
        if (cbbakso.isSelected()) {
            jumlahpesanan = Integer.parseInt(tfbakso.getText());
            total += jumlahpesanan * 13000;
        }
        if (cbnasigoreng.isSelected()) {
            jumlahpesanan = Integer.parseInt(tfnasigoreng.getText());
            total += jumlahpesanan * 10000;
        }
        if (cbmartabak.isSelected()) {
            jumlahpesanan = Integer.parseInt(tfmartabak.getText());
            total += jumlahpesanan * 5000;
        }

        tfhitung.setText(String.valueOf(total));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan jumlah yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnhitungActionPerformed

    private void cbmieayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmieayamActionPerformed
        // TODO add your handling code here:
        if (cbmieayam.isSelected()== true){
            tfmieayam.setEditable(true);
        }else{
            tfmieayam.setEditable(false);
            tfmieayam.setText("");
        }
    }//GEN-LAST:event_cbmieayamActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void cbbaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbaksoActionPerformed
        // TODO add your handling code here:
        if (cbbakso.isSelected()== true){
            tfbakso.setEditable(true);
        }else{
            tfbakso.setEditable(false);
            tfbakso.setText("");
        }
    }//GEN-LAST:event_cbbaksoActionPerformed

    private void cbnasigorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnasigorengActionPerformed
        // TODO add your handling code here:
        if (cbnasigoreng.isSelected()== true){
            tfnasigoreng.setEditable(true);
        }else{
            tfnasigoreng.setEditable(false);
            tfnasigoreng.setText("");
        }
    }//GEN-LAST:event_cbnasigorengActionPerformed

    private void cbmartabakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmartabakActionPerformed
        // TODO add your handling code here:
        if (cbmartabak.isSelected()== true){
            tfmartabak.setEditable(true);
        }else{
            tfmartabak.setEditable(false);
            tfmartabak.setText("");
        }
    }//GEN-LAST:event_cbmartabakActionPerformed

    private void btnbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihActionPerformed
        // TODO add your handling code here:
        cbmieayam.setSelected(false);
        cbbakso.setSelected(false);
        cbnasigoreng.setSelected(false);
        cbmartabak.setSelected(false);

        tfmieayam.setText("");
        tfbakso.setText("");
        tfnasigoreng.setText("");
        tfmartabak.setText("");
        tfhitung.setText("");

        tfmieayam.setEditable(false);
        tfbakso.setEditable(false);
        tfnasigoreng.setEditable(false);
        tfmartabak.setEditable(false);
    }//GEN-LAST:event_btnbersihActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new K_Swing2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbersih;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JCheckBox cbbakso;
    private javax.swing.JCheckBox cbmartabak;
    private javax.swing.JCheckBox cbmieayam;
    private javax.swing.JCheckBox cbnasigoreng;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField tfbakso;
    private javax.swing.JTextField tfhitung;
    private javax.swing.JTextField tfmartabak;
    private javax.swing.JTextField tfmieayam;
    private javax.swing.JTextField tfnasigoreng;
    // End of variables declaration//GEN-END:variables
}
